### PR TITLE
Firebase (sign-in, register, add patients)

### PR DESCRIPTION
**Pull request by kagibson**
I've integrated my Firebase demo app into the project layout. I've tried to fix any issues I've noticed so far and I've tried to right smart code. Please clone the branch and try to find any issues, or let me know if any of the code needs work. I'm not sure if the pods will cause any issues. Pull this branch using the terminal and then work from STiOS.xcworkspace from now on.

### CODE REVIEW

**Comment by rn10rd9** [comment]
Looks good Kurtis

**Comment by kagibson** [comment]
Were you able to run the app properly?

**Comment by kt0rres** [comment]
Hi Kurtis,

I apologize for the lateness of this, but I have attached what I believe should be added/"tweaked". First off, the code looks fine. I don't see anything worth noting at the moment!

However, I feel we should consider the following:
   1. I have attached a file called "Touch-up-Outside.png", which shows a list of actions that we can use on the textboxes. As we have discussed previously, we can use methods from this list as a way to avoid using the (non-trivial) enter button press that is required when registering the user onto the firebase database.

Touch_up_Outside.png:
touch_up_outside

   2. Having looked at the view controller swift files I don't think a sign out feature has been implemented. From what I gather, in the PatientListViewController.swift file, we just need to add a press function to the icon in the top left corner (the back arrow, as I was not able to find a meaningful default icon for it) and insert the following:

try! FIRAuth.auth()!.signOut() 

and we can insert one of the following to immediately jump to a view controller (SignInViewController in this case)

if let storyboard = self.storyboard {
    let vc = storyboard.instantiateViewControllerWithIdentifier("SignInViewController") as! UINavigationController
        self.presentViewController(vc, animated: false, completion: nil)
    }

or we can also use the unwind segue call shown in here:
http://stackoverflow.com/questions/30052587/how-can-i-go-back-to-the-initial-view-controller-in-swift

3. Lastly, we should try to keep things centered. Apple has a weird autolayout feature that has been a pain in my side the entirety of my apple development career. The missing auto layout is evident if we were to run a simulation on a bigger device screen (iphone 7, ipad, etc) or on the actual device. I will record the results when I upload the app onto the idevices. These can be fixed with constraints which can be found in the bottom right hand bar underneath the storyboard screen. I have attached a screenshot of the buttons in particular and the displacement of all the fields in the register screen (in particular).

constraint_buttons
fix_constraints

Kristian.

**Comment by kt0rres** [comment]
In the above the last two pictures are confusing because of the lack of spacing between them. To clarify, the first picture are the buttons that aid with constraints and stuff and the second is the screenshot of the field displacements.

If you have any questions, feel free to contact me and we can discuss further!

**Pull request merged**
